# Generated by Django 4.2 on 2023-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follewing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
