# Generated by Django 4.2 on 2023-04-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_follewing_user_follower_user_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follewing',
            new_name='following',
        ),
    ]
